name: Extract Cache
description: "Extracts the cached data from the docker build(x|kit) process"
inputs:
  cache-source:
    default: cache
    description: "Where the cache is stored in the calling workspace. Default: `cache`"
  scratch-dir:
    default: scratch
    description: "Where the action is stores some temporary files for its processing. Default: `scratch`"
runs:
  using: composite
  steps:
    - name: Prepare Timestamp for Layer Cache Busting
      shell: bash
      run: |
        date --iso=ns | tee ${{ inputs.scratch-dir }}/buildstamp
    - name: Prepare Dancefile to Access Caches
      shell: bash
      run: |
        cat > ${{ inputs.scratch-dir }}/Dancefile.extract <<EOF
        FROM busybox:1
        COPY buildstamp buildstamp
        RUN --mount=type=cache,id=deps_cargo_index,target=/usr/local/cargo/registry/index \
            --mount=type=cache,id=deps_cargo_cache,target=/usr/local/cargo/registry/cache \
            --mount=type=cache,id=deps_cargo_git,target=/usr/local/cargo/git/db \
            --mount=type=cache,id=deps_target,target=/platform/target \
            mkdir -p /var/dance-cache/registry/index && \
            mkdir -p /var/dance-cache/registry/cache && \
            mkdir -p /var/dance-cache/git/db && \
            mkdir -p /var/dance-cache/target && \
            ls -lha /usr/local/cargo/registry/index && \
            ls -lha /usr/local/cargo/registry/cache && \
            ls -lha /usr/local/cargo/git/db && \
            ls -lha /platform/target && \
            echo "timestamps after build, before copy from cachedir"
            find /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/ -exec stat -c '%n %Y' {} + && \
            cp -R /usr/local/cargo/registry/index/. /var/dance-cache/registry/index || true && \
            cp -R /usr/local/cargo/registry/cache/. /var/dance-cache/registry/cache || true && \
            cp -R /usr/local/cargo/git/db/. /var/dance-cache/git/db || true && \
            cp -R /platform/target/. /var/dance-cache/target || true && \
            echo "timestamps after build, after copy from cachedir"
        EOF
        cat ${{ inputs.scratch-dir }}/Dancefile.extract
    - name: Extract Data into buildx context
      shell: bash
      run: |
        docker buildx build -f ${{ inputs.scratch-dir }}/Dancefile.extract --tag dance:extract --load ${{ inputs.scratch-dir }}
    - name: Create Extraction Image
      shell: bash
      run: |
        docker rm -f cache-container && docker create -ti --name cache-container dance:extract
    - name: Unpack Docker Image into Scratch
      shell: bash
      run: |
        docker cp -L cache-container:/var/dance-cache - | tar -x -C ${{ inputs.scratch-dir }}
    - name: Move Cache into Its Place
      shell: bash
      run: |
        sudo rm -rf ${{ inputs.cache-source }}
        mv ${{ inputs.scratch-dir }}/dance-cache ${{ inputs.cache-source }}
        echo "timestamps after build, after copy out from built cache image with tar"
        find ${{ inputs.cache-source }}/registry/src/github.com-1ecc6299db9ec823/ -printf '%p %C@\n' && \
